variable "vpc" {}
variable "vpc_default_vpc_id" {}
variable "default_vpc_cidr" {}
variable "default_vpc_route_table_id" {}
variable "tags" {}
variable "env" {}
variable "alb" {}
variable "docdb" {}
variable "engine_version" {}